# Auto-generated by ATF2e16_single_track notebook.

simulation_name = "QUASI3D"

shape = "rectangle"

iterations = 40000

# mode 0 is the wakefield, mode 1 is the laser, mode -1 is both.
mode = -1

fname = "Bryson.npz"

debugmode = False

# Probe centered at the following initial coordinates, in c/omega_p.
x_c = 3
y_c = 0.1
xi_c = 3

# Initial momentum.
px_0 = 110
py_0 = 0
pz_0 = 0

# Screen distances from z-axis of plasma cell, in mm.
x_s = [10, 50, 100, 250, 500]

# Shape parameters.
s1 = 0.1  # in y
s2 = 0.1  # in xi

# Densities.
ydensity = 5
xidensity = 5
xdensity = 1
resolution = None

# Quasi3D simulation parameters.
quasi_id = "000026"
quasi_data_dir = "data/OSIRIS/ATF2e16"
quasi_density = 2e22
quasi_propagation_speed = 1.0
dt_safety_factor = 0.1
