# Auto-generated by ATF2e16_single_track notebook.
simulation_name = "QUASI3D"

shape = "rectangle"

iterations = 40000

# mode 0 is the wakefield, mode 1 is the laser, mode -1 is both.
mode = -1

fname = "200-SW-Run.npz"

debugmode = False

# Probe centered at the following initial coordinates, in c/omega_p.
x_c = -1
y_c = 0
xi_c = -7.3

# Initial momentum.
px_0 = 110
py_0 = 0
pz_0 = 0

# Screen distances from z-axis of plasma cell, in mm.
x_s = [10, 25, 50, 75, 100,]

# Shape parameters.
s1 = 1  # in y
s2 = 2  # in xi

# Densities.
ydensity = 10
xidensity = 20
xdensity = 1
resolution = None

# Quasi3D simulation parameters.
quasi_id = "000130"
quasi_data_dir = "data/OSIRIS/Quasi3D"
quasi_density = 1e21 #in m^-3
quasi_propagation_speed = 1.0
dt_safety_factor = 0.1 #this is multiplied by dz
